version: '3'
services:
  web:
    container_name: react-web-app
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    networks:
      - frontend
    stdin_open: true
  server:
    container_name: react-web-app-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    networks:
      - backend
  nginx:
    container_name: react-web-app-nginx
    build:
      context:  .
      dockerfile: Dockerfile
    ports:
      - "81:80"
    networks:
      - frontend
      - backend
networks:
  frontend:
  backend:
