version: '3'
services:
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/books 
    networks:
      - backend
    restart:
      always
  db:
    container_name: postgres
    image: "postgres:10.4"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=books
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - backend
    restart:
      always
networks:
  backend:
