version: '3'
services:
  postgres:
    container_name: react-web-app-postgres
    image: "postgres:9.5"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=books
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
